config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: %i(
    confirmations
    omniauth_callbacks
    passwords
    registrations
    sessions
    unlocks
  ).map { |controller| { controller => "users/#{controller}" } }.reduce(:merge)

  devise_scope :user do
    authenticated :user do
      root to: 'home#homepage'
    end

    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end
  end


  devise_for :api_users, path: '', controllers: {
    sessions: 'api/users/sessions',
    registrations: 'api/users/registrations'
  }, skip: %i(sessions registrations)

  devise_scope :api_user do
    defaults format: :json do
      post 'api/users/sign_up', to: 'api/users/registrations#create'
      post 'api/users/sign_in', to: 'api/users/sessions#create'
      delete 'api/users/sign_out', to: 'api/users/sessions#destroy'
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  authenticate :user, ->(user) { user.allowed_to_access_dashboards? } do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: '/pghero'
  end

  mount Rswag::Ui::Engine, at: '/api-docs'
  mount Rswag::Api::Engine, at: '/api-docs'


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resource :two_factor_authentication_settings, except: %i(index show)

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        resources :users, only: %i(index show)
        get '/current_user', to: 'users#current_user'
      end
    end
  end

  resources :users, except: :destroy

  get 'pdf', to: 'pdfs#print'
end

app/controllers/two_factor_authentication_settings_controller.rb
# frozen_string_literal: true

class TwoFactorAuthenticationSettingsController < ApplicationController
  def new
    if current_user.otp_required_for_login
      flash[:alert] = I18n.t('two_factor_auth_settings.already_enabled')

      return redirect_to edit_user_registration_path
    end

    current_user.generate_two_factor_auth_secret_if_missing!
  end

  def create
    unless current_user.valid_password?(two_factor_auth_params[:password])
      flash.now[:alert] = I18n.t('two_factor_auth_settings.password_invalid')

      return render :new
    end

    if current_user.validate_and_consume_otp!(two_factor_auth_params[:code])
      current_user.enable_two_factor_auth!

      flash[:notice] = I18n.t('two_factor_auth_settings.two_factor_auth_enabled')

      redirect_to edit_two_factor_authentication_settings_path
    else
      flash.now[:alert] = I18n.t('two_factor_auth_settings.two_factor_auth_code_invalid')

      render :new
    end
  end

  def edit
    unless current_user.otp_required_for_login
      flash[:alert] = I18n.t('two_factor_auth_settings.enable_two_factor_auth')

      return redirect_to new_two_factor_authentication_settings_path
    end

    if current_user.two_factor_auth_backup_codes_generated?
      flash[:alert] = I18n.t('two_factor_auth_settings.backup_codes_seen')

      return redirect_to edit_user_registration_path
    end

    @backup_codes = current_user.generate_otp_backup_codes!

    current_user.save!
  end

  def destroy
    if current_user.disable_two_factor_auth!
      flash[:notice] = I18n.t('two_factor_auth_settings.two_factor_auth_disabled')

      redirect_to edit_user_registration_path
    else
      flash[:alert] = I18n.t('two_factor_auth_settings.could_not_disable_two_factor_auth')

      redirect_to root_path
    end
  end

  private

  def two_factor_auth_params
    @two_factor_auth_params ||= params.require(:two_factor_auth).permit(:code, :password)
  end
end

app/views/two_factor_authentication_settings/edit.html.erb
<p>Two Factor Authentication</p>
<p>Backup Codes</p>
<p>Keep these backup codes safe in case you lose access to your authenticator app:</p>
<% @backup_codes.each do |code| %>
  <p><%=code %></p>
<% end %>

<p>Two Factor Auth Setup Complete</p>
<p>Two factor authentication has been successfully enabled.</p>
<%= link_to('Return to account settings', edit_user_registration_path) %>

app/views/two_factor_authentication_settings/new.html.erb
<p>Two Factor Authentication</p>

<p>1. Scan QR Code</p>
<p>Please, scan the below QR code using an OTP compatible app (such as Google Authenticator or Authy)</p>
<p><%= qr_code_as_svg(current_user.two_factor_auth_qr_code_uri)%></p>
<p>If you cannot scan, please enter the following code manually: <code><%= current_user.otp_secret%></code></p>

<p>2. Confirm OTP Code</p>
<p>Please, confirm that your authentication application is working by entering a generated code below</p>

<%= simple_form_for(:two_factor_auth, url: two_factor_authentication_settings_path, method: :post) do |f| %>
  <%= f.input :code %>
  <%= f.input :password, label: 'Enter your current password' %>
  <%= f.submit 'Confirm and Enable Two Factor Auth' %>
<% end %>